application:
  name: TEST ENVIROMENT
  
# Database h2 connection
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console
      
# Dependencies
#    <dependency>
#      <groupId>org.springframework.boot</groupId>
#      <artifactId>spring-boot-starter-data-jpa</artifactId>
#    </dependency>
#    
#    <dependency>
#      <groupId>com.h2database</groupId>
#      <artifactId>h2</artifactId>
#    </dependency>
