CREATE TABLE CLIENTES(
    ID_CLIENTE INTEGER PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE PRODUTOS(
    ID_PRODUTO INTEGER PRIMARY KEY AUTO_INCREMENT,
    PRECO_UNITARIO NUMERIC(20,2),
    DESCRICAO VARCHAR(100)
);

CREATE TABLE PEDIDOS(
    ID_PEDIDO INTEGER PRIMARY KEY AUTO_INCREMENT,
    CLIENTE_ID INTEGER REFERENCES CLIENTES (ID_CLIENTE),
    TOTAL NUMERIC(20,2),
    DATA_PEDIDO TIMESTAMP
);

CREATE TABLE ITEM_PEDIDOS(
    ID_ITEM_PEDIDO INTEGER PRIMARY KEY AUTO_INCREMENT,
    PEDIDO_ID INTEGER REFERENCES PEDIDOS (ID_PEDIDO),
    PRODUTO_ID INTEGER REFERENCES PRODUTOS (ID_PRODUTO),
    QUANTIDADE INTEGER
    
);
